include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.graphql.dart"
    - "**/*.mocks.dart"
    - "**/generated/**"

  errors:
    todo: ignore
    unnecessary_this: ignore
    avoid_empty_else: error
    avoid_function_literals_in_foreach_calls: ignore

linter:
  rules:
    # Error prevention
    avoid_print: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true

    # Documentation
    package_api_docs: true
    # public_member_api_docs: true

    prefer_single_quotes: true
    require_trailing_commas: true
    always_declare_return_types: true
    sort_child_properties_last: true
    super_goes_last: false
    use_decorated_box: true
    use_super_parameters: true
    prefer_final_fields: true
    matching_super_parameters: true
    sort_constructors_first: true
    always_put_control_body_on_new_line: true
    use_key_in_widget_constructors: true
    directives_ordering: true
    sort_pub_dependencies: true
    always_put_required_named_parameters_first: false
