include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.graphql.dart"
    - "**/*.mocks.dart"
    - "**/generated/**"

  errors:
    todo: ignore
    unnecessary_this: ignore
    avoid_empty_else: error
    avoid_function_literals_in_foreach_calls: ignore

  language:
      strict-casts: true
      strict-inference: true
      strict-raw-types: true

  strong-mode:
      implicit-casts: false

dart_code_metrics:
  rules:
    - max-line-length: 120
    - prefer-trailing-comma: true

linter:
  rules:    
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: false
    avoid_print: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    matching_super_parameters: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    super_goes_last: false
    use_decorated_box: true
    use_key_in_widget_constructors: true
    use_super_parameters: true
